/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BrevoDotNet.Model;
using BrevoDotNet.Client;
using System.Reflection;

namespace BrevoDotNet.Test.Model
{
    /// <summary>
    ///  Class for testing GetExtendedList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetExtendedListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetExtendedList
        //private GetExtendedList instance;

        public GetExtendedListTests()
        {
            // TODO uncomment below to create an instance of GetExtendedList
            //instance = new GetExtendedList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetExtendedList
        /// </summary>
        [Fact]
        public void GetExtendedListInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetExtendedList
            //Assert.IsType<GetExtendedList>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'TotalBlacklisted'
        /// </summary>
        [Fact]
        public void TotalBlacklistedTest()
        {
            // TODO unit test for the property 'TotalBlacklisted'
        }

        /// <summary>
        /// Test the property 'TotalSubscribers'
        /// </summary>
        [Fact]
        public void TotalSubscribersTest()
        {
            // TODO unit test for the property 'TotalSubscribers'
        }

        /// <summary>
        /// Test the property 'FolderId'
        /// </summary>
        [Fact]
        public void FolderIdTest()
        {
            // TODO unit test for the property 'FolderId'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'CampaignStats'
        /// </summary>
        [Fact]
        public void CampaignStatsTest()
        {
            // TODO unit test for the property 'CampaignStats'
        }

        /// <summary>
        /// Test the property 'DynamicList'
        /// </summary>
        [Fact]
        public void DynamicListTest()
        {
            // TODO unit test for the property 'DynamicList'
        }
    }
}
