/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BrevoDotNet.Model;
using BrevoDotNet.Client;
using System.Reflection;

namespace BrevoDotNet.Test.Model
{
    /// <summary>
    ///  Class for testing GetWhatsappCampaignsCampaignsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetWhatsappCampaignsCampaignsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetWhatsappCampaignsCampaignsInner
        //private GetWhatsappCampaignsCampaignsInner instance;

        public GetWhatsappCampaignsCampaignsInnerTests()
        {
            // TODO uncomment below to create an instance of GetWhatsappCampaignsCampaignsInner
            //instance = new GetWhatsappCampaignsCampaignsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetWhatsappCampaignsCampaignsInner
        /// </summary>
        [Fact]
        public void GetWhatsappCampaignsCampaignsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetWhatsappCampaignsCampaignsInner
            //Assert.IsType<GetWhatsappCampaignsCampaignsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CampaignName'
        /// </summary>
        [Fact]
        public void CampaignNameTest()
        {
            // TODO unit test for the property 'CampaignName'
        }

        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }

        /// <summary>
        /// Test the property 'CampaignStatus'
        /// </summary>
        [Fact]
        public void CampaignStatusTest()
        {
            // TODO unit test for the property 'CampaignStatus'
        }

        /// <summary>
        /// Test the property 'ScheduledAt'
        /// </summary>
        [Fact]
        public void ScheduledAtTest()
        {
            // TODO unit test for the property 'ScheduledAt'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'ModifiedAt'
        /// </summary>
        [Fact]
        public void ModifiedAtTest()
        {
            // TODO unit test for the property 'ModifiedAt'
        }

        /// <summary>
        /// Test the property 'ErrorReason'
        /// </summary>
        [Fact]
        public void ErrorReasonTest()
        {
            // TODO unit test for the property 'ErrorReason'
        }

        /// <summary>
        /// Test the property 'InvalidatedContacts'
        /// </summary>
        [Fact]
        public void InvalidatedContactsTest()
        {
            // TODO unit test for the property 'InvalidatedContacts'
        }

        /// <summary>
        /// Test the property 'ReadPercentage'
        /// </summary>
        [Fact]
        public void ReadPercentageTest()
        {
            // TODO unit test for the property 'ReadPercentage'
        }

        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Fact]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }
    }
}
