/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BrevoDotNet.Model;
using BrevoDotNet.Client;
using System.Reflection;

namespace BrevoDotNet.Test.Model
{
    /// <summary>
    ///  Class for testing SendSmtpEmail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendSmtpEmailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendSmtpEmail
        //private SendSmtpEmail instance;

        public SendSmtpEmailTests()
        {
            // TODO uncomment below to create an instance of SendSmtpEmail
            //instance = new SendSmtpEmail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendSmtpEmail
        /// </summary>
        [Fact]
        public void SendSmtpEmailInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendSmtpEmail
            //Assert.IsType<SendSmtpEmail>(instance);
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Fact]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }

        /// <summary>
        /// Test the property 'Bcc'
        /// </summary>
        [Fact]
        public void BccTest()
        {
            // TODO unit test for the property 'Bcc'
        }

        /// <summary>
        /// Test the property 'Cc'
        /// </summary>
        [Fact]
        public void CcTest()
        {
            // TODO unit test for the property 'Cc'
        }

        /// <summary>
        /// Test the property 'HtmlContent'
        /// </summary>
        [Fact]
        public void HtmlContentTest()
        {
            // TODO unit test for the property 'HtmlContent'
        }

        /// <summary>
        /// Test the property 'TextContent'
        /// </summary>
        [Fact]
        public void TextContentTest()
        {
            // TODO unit test for the property 'TextContent'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'ReplyTo'
        /// </summary>
        [Fact]
        public void ReplyToTest()
        {
            // TODO unit test for the property 'ReplyTo'
        }

        /// <summary>
        /// Test the property 'Attachment'
        /// </summary>
        [Fact]
        public void AttachmentTest()
        {
            // TODO unit test for the property 'Attachment'
        }

        /// <summary>
        /// Test the property 'Headers'
        /// </summary>
        [Fact]
        public void HeadersTest()
        {
            // TODO unit test for the property 'Headers'
        }

        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }

        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
    }
}
