// <auto-generated>
/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using BrevoDotNet.Client;

namespace BrevoDotNet.Model
{
    /// <summary>
    /// GetStatsByDevice
    /// </summary>
    public partial class GetStatsByDevice : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetStatsByDevice" /> class.
        /// </summary>
        /// <param name="desktop">Statistics of the campaign on the basis of desktop devices</param>
        /// <param name="mobile">Statistics of the campaign on the basis of mobile devices</param>
        /// <param name="tablet">Statistics of the campaign on the basis of tablet devices</param>
        /// <param name="unknown">Statistics of the campaign on the basis of unknown devices</param>
        [JsonConstructor]
        public GetStatsByDevice(Option<Dictionary<string, GetDeviceBrowserStats>?> desktop = default, Option<Dictionary<string, GetDeviceBrowserStats>?> mobile = default, Option<Dictionary<string, GetDeviceBrowserStats>?> tablet = default, Option<Dictionary<string, GetDeviceBrowserStats>?> unknown = default)
        {
            DesktopOption = desktop;
            MobileOption = mobile;
            TabletOption = tablet;
            UnknownOption = unknown;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Desktop
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, GetDeviceBrowserStats>?> DesktopOption { get; private set; }

        /// <summary>
        /// Statistics of the campaign on the basis of desktop devices
        /// </summary>
        /// <value>Statistics of the campaign on the basis of desktop devices</value>
        [JsonPropertyName("desktop")]
        public Dictionary<string, GetDeviceBrowserStats>? Desktop { get { return this.DesktopOption; } set { this.DesktopOption = new(value); } }

        /// <summary>
        /// Used to track the state of Mobile
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, GetDeviceBrowserStats>?> MobileOption { get; private set; }

        /// <summary>
        /// Statistics of the campaign on the basis of mobile devices
        /// </summary>
        /// <value>Statistics of the campaign on the basis of mobile devices</value>
        [JsonPropertyName("mobile")]
        public Dictionary<string, GetDeviceBrowserStats>? Mobile { get { return this.MobileOption; } set { this.MobileOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tablet
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, GetDeviceBrowserStats>?> TabletOption { get; private set; }

        /// <summary>
        /// Statistics of the campaign on the basis of tablet devices
        /// </summary>
        /// <value>Statistics of the campaign on the basis of tablet devices</value>
        [JsonPropertyName("tablet")]
        public Dictionary<string, GetDeviceBrowserStats>? Tablet { get { return this.TabletOption; } set { this.TabletOption = new(value); } }

        /// <summary>
        /// Used to track the state of Unknown
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, GetDeviceBrowserStats>?> UnknownOption { get; private set; }

        /// <summary>
        /// Statistics of the campaign on the basis of unknown devices
        /// </summary>
        /// <value>Statistics of the campaign on the basis of unknown devices</value>
        [JsonPropertyName("unknown")]
        public Dictionary<string, GetDeviceBrowserStats>? Unknown { get { return this.UnknownOption; } set { this.UnknownOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetStatsByDevice {\n");
            sb.Append("  Desktop: ").Append(Desktop).Append("\n");
            sb.Append("  Mobile: ").Append(Mobile).Append("\n");
            sb.Append("  Tablet: ").Append(Tablet).Append("\n");
            sb.Append("  Unknown: ").Append(Unknown).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetStatsByDevice" />
    /// </summary>
    public class GetStatsByDeviceJsonConverter : JsonConverter<GetStatsByDevice>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetStatsByDevice" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetStatsByDevice Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Dictionary<string, GetDeviceBrowserStats>?> desktop = default;
            Option<Dictionary<string, GetDeviceBrowserStats>?> mobile = default;
            Option<Dictionary<string, GetDeviceBrowserStats>?> tablet = default;
            Option<Dictionary<string, GetDeviceBrowserStats>?> unknown = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "desktop":
                            desktop = new Option<Dictionary<string, GetDeviceBrowserStats>?>(JsonSerializer.Deserialize<Dictionary<string, GetDeviceBrowserStats>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "mobile":
                            mobile = new Option<Dictionary<string, GetDeviceBrowserStats>?>(JsonSerializer.Deserialize<Dictionary<string, GetDeviceBrowserStats>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "tablet":
                            tablet = new Option<Dictionary<string, GetDeviceBrowserStats>?>(JsonSerializer.Deserialize<Dictionary<string, GetDeviceBrowserStats>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "unknown":
                            unknown = new Option<Dictionary<string, GetDeviceBrowserStats>?>(JsonSerializer.Deserialize<Dictionary<string, GetDeviceBrowserStats>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (desktop.IsSet && desktop.Value == null)
                throw new ArgumentNullException(nameof(desktop), "Property is not nullable for class GetStatsByDevice.");

            if (mobile.IsSet && mobile.Value == null)
                throw new ArgumentNullException(nameof(mobile), "Property is not nullable for class GetStatsByDevice.");

            if (tablet.IsSet && tablet.Value == null)
                throw new ArgumentNullException(nameof(tablet), "Property is not nullable for class GetStatsByDevice.");

            if (unknown.IsSet && unknown.Value == null)
                throw new ArgumentNullException(nameof(unknown), "Property is not nullable for class GetStatsByDevice.");

            return new GetStatsByDevice(desktop, mobile, tablet, unknown);
        }

        /// <summary>
        /// Serializes a <see cref="GetStatsByDevice" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getStatsByDevice"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetStatsByDevice getStatsByDevice, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getStatsByDevice, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetStatsByDevice" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getStatsByDevice"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetStatsByDevice getStatsByDevice, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getStatsByDevice.DesktopOption.IsSet && getStatsByDevice.Desktop == null)
                throw new ArgumentNullException(nameof(getStatsByDevice.Desktop), "Property is required for class GetStatsByDevice.");

            if (getStatsByDevice.MobileOption.IsSet && getStatsByDevice.Mobile == null)
                throw new ArgumentNullException(nameof(getStatsByDevice.Mobile), "Property is required for class GetStatsByDevice.");

            if (getStatsByDevice.TabletOption.IsSet && getStatsByDevice.Tablet == null)
                throw new ArgumentNullException(nameof(getStatsByDevice.Tablet), "Property is required for class GetStatsByDevice.");

            if (getStatsByDevice.UnknownOption.IsSet && getStatsByDevice.Unknown == null)
                throw new ArgumentNullException(nameof(getStatsByDevice.Unknown), "Property is required for class GetStatsByDevice.");

            if (getStatsByDevice.DesktopOption.IsSet)
            {
                writer.WritePropertyName("desktop");
                JsonSerializer.Serialize(writer, getStatsByDevice.Desktop, jsonSerializerOptions);
            }
            if (getStatsByDevice.MobileOption.IsSet)
            {
                writer.WritePropertyName("mobile");
                JsonSerializer.Serialize(writer, getStatsByDevice.Mobile, jsonSerializerOptions);
            }
            if (getStatsByDevice.TabletOption.IsSet)
            {
                writer.WritePropertyName("tablet");
                JsonSerializer.Serialize(writer, getStatsByDevice.Tablet, jsonSerializerOptions);
            }
            if (getStatsByDevice.UnknownOption.IsSet)
            {
                writer.WritePropertyName("unknown");
                JsonSerializer.Serialize(writer, getStatsByDevice.Unknown, jsonSerializerOptions);
            }
        }
    }
}
