// <auto-generated>
/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using BrevoDotNet.Client;

namespace BrevoDotNet.Model
{
    /// <summary>
    /// GetSmsCampaigns
    /// </summary>
    public partial class GetSmsCampaigns : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSmsCampaigns" /> class.
        /// </summary>
        /// <param name="count">Number of SMS campaigns retrieved</param>
        /// <param name="campaigns">campaigns</param>
        [JsonConstructor]
        public GetSmsCampaigns(long count, Option<List<GetSmsCampaignsCampaignsInner>?> campaigns = default)
        {
            Count = count;
            CampaignsOption = campaigns;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Number of SMS campaigns retrieved
        /// </summary>
        /// <value>Number of SMS campaigns retrieved</value>
        /* <example>12</example> */
        [JsonPropertyName("count")]
        public long Count { get; set; }

        /// <summary>
        /// Used to track the state of Campaigns
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<GetSmsCampaignsCampaignsInner>?> CampaignsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Campaigns
        /// </summary>
        [JsonPropertyName("campaigns")]
        public List<GetSmsCampaignsCampaignsInner>? Campaigns { get { return this.CampaignsOption; } set { this.CampaignsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetSmsCampaigns {\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  Campaigns: ").Append(Campaigns).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetSmsCampaigns" />
    /// </summary>
    public class GetSmsCampaignsJsonConverter : JsonConverter<GetSmsCampaigns>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetSmsCampaigns" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetSmsCampaigns Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> count = default;
            Option<List<GetSmsCampaignsCampaignsInner>?> campaigns = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "count":
                            count = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "campaigns":
                            campaigns = new Option<List<GetSmsCampaignsCampaignsInner>?>(JsonSerializer.Deserialize<List<GetSmsCampaignsCampaignsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!count.IsSet)
                throw new ArgumentException("Property is required for class GetSmsCampaigns.", nameof(count));

            if (count.IsSet && count.Value == null)
                throw new ArgumentNullException(nameof(count), "Property is not nullable for class GetSmsCampaigns.");

            if (campaigns.IsSet && campaigns.Value == null)
                throw new ArgumentNullException(nameof(campaigns), "Property is not nullable for class GetSmsCampaigns.");

            return new GetSmsCampaigns(count.Value!.Value!, campaigns);
        }

        /// <summary>
        /// Serializes a <see cref="GetSmsCampaigns" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSmsCampaigns"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetSmsCampaigns getSmsCampaigns, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getSmsCampaigns, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetSmsCampaigns" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSmsCampaigns"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetSmsCampaigns getSmsCampaigns, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getSmsCampaigns.CampaignsOption.IsSet && getSmsCampaigns.Campaigns == null)
                throw new ArgumentNullException(nameof(getSmsCampaigns.Campaigns), "Property is required for class GetSmsCampaigns.");

            writer.WriteNumber("count", getSmsCampaigns.Count);

            if (getSmsCampaigns.CampaignsOption.IsSet)
            {
                writer.WritePropertyName("campaigns");
                JsonSerializer.Serialize(writer, getSmsCampaigns.Campaigns, jsonSerializerOptions);
            }
        }
    }
}
