// <auto-generated>
/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using BrevoDotNet.Client;

namespace BrevoDotNet.Model
{
    /// <summary>
    /// GetTransacSmsReportReportsInner
    /// </summary>
    public partial class GetTransacSmsReportReportsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetTransacSmsReportReportsInner" /> class.
        /// </summary>
        /// <param name="date">Date for which statistics are retrieved</param>
        /// <param name="requests">Number of requests for the date</param>
        /// <param name="delivered">Number of delivered SMS for the date</param>
        /// <param name="hardBounces">Number of hardbounces for the date</param>
        /// <param name="softBounces">Number of softbounces for the date</param>
        /// <param name="blocked">Number of blocked contact for the date</param>
        /// <param name="unsubscribed">Number of unsubscription for the date</param>
        /// <param name="replied">Number of answered SMS for the date</param>
        /// <param name="accepted">Number of accepted for the date</param>
        /// <param name="rejected">Number of rejected for the date</param>
        [JsonConstructor]
        public GetTransacSmsReportReportsInner(DateOnly date, long requests, long delivered, long hardBounces, long softBounces, long blocked, long unsubscribed, long replied, long accepted, long rejected)
        {
            Date = date;
            Requests = requests;
            Delivered = delivered;
            HardBounces = hardBounces;
            SoftBounces = softBounces;
            Blocked = blocked;
            Unsubscribed = unsubscribed;
            Replied = replied;
            Accepted = accepted;
            Rejected = rejected;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Date for which statistics are retrieved
        /// </summary>
        /// <value>Date for which statistics are retrieved</value>
        /* <example>Fri Mar 17 00:00:00 UTC 2017</example> */
        [JsonPropertyName("date")]
        public DateOnly Date { get; set; }

        /// <summary>
        /// Number of requests for the date
        /// </summary>
        /// <value>Number of requests for the date</value>
        /* <example>87</example> */
        [JsonPropertyName("requests")]
        public long Requests { get; set; }

        /// <summary>
        /// Number of delivered SMS for the date
        /// </summary>
        /// <value>Number of delivered SMS for the date</value>
        /* <example>85</example> */
        [JsonPropertyName("delivered")]
        public long Delivered { get; set; }

        /// <summary>
        /// Number of hardbounces for the date
        /// </summary>
        /// <value>Number of hardbounces for the date</value>
        /* <example>1</example> */
        [JsonPropertyName("hardBounces")]
        public long HardBounces { get; set; }

        /// <summary>
        /// Number of softbounces for the date
        /// </summary>
        /// <value>Number of softbounces for the date</value>
        /* <example>1</example> */
        [JsonPropertyName("softBounces")]
        public long SoftBounces { get; set; }

        /// <summary>
        /// Number of blocked contact for the date
        /// </summary>
        /// <value>Number of blocked contact for the date</value>
        /* <example>0</example> */
        [JsonPropertyName("blocked")]
        public long Blocked { get; set; }

        /// <summary>
        /// Number of unsubscription for the date
        /// </summary>
        /// <value>Number of unsubscription for the date</value>
        /* <example>1</example> */
        [JsonPropertyName("unsubscribed")]
        public long Unsubscribed { get; set; }

        /// <summary>
        /// Number of answered SMS for the date
        /// </summary>
        /// <value>Number of answered SMS for the date</value>
        /* <example>2</example> */
        [JsonPropertyName("replied")]
        public long Replied { get; set; }

        /// <summary>
        /// Number of accepted for the date
        /// </summary>
        /// <value>Number of accepted for the date</value>
        /* <example>85</example> */
        [JsonPropertyName("accepted")]
        public long Accepted { get; set; }

        /// <summary>
        /// Number of rejected for the date
        /// </summary>
        /// <value>Number of rejected for the date</value>
        /* <example>1</example> */
        [JsonPropertyName("rejected")]
        public long Rejected { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetTransacSmsReportReportsInner {\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Requests: ").Append(Requests).Append("\n");
            sb.Append("  Delivered: ").Append(Delivered).Append("\n");
            sb.Append("  HardBounces: ").Append(HardBounces).Append("\n");
            sb.Append("  SoftBounces: ").Append(SoftBounces).Append("\n");
            sb.Append("  Blocked: ").Append(Blocked).Append("\n");
            sb.Append("  Unsubscribed: ").Append(Unsubscribed).Append("\n");
            sb.Append("  Replied: ").Append(Replied).Append("\n");
            sb.Append("  Accepted: ").Append(Accepted).Append("\n");
            sb.Append("  Rejected: ").Append(Rejected).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetTransacSmsReportReportsInner" />
    /// </summary>
    public class GetTransacSmsReportReportsInnerJsonConverter : JsonConverter<GetTransacSmsReportReportsInner>
    {
        /// <summary>
        /// The format to use to serialize Date
        /// </summary>
        public static string DateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="GetTransacSmsReportReportsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetTransacSmsReportReportsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DateOnly?> date = default;
            Option<long?> requests = default;
            Option<long?> delivered = default;
            Option<long?> hardBounces = default;
            Option<long?> softBounces = default;
            Option<long?> blocked = default;
            Option<long?> unsubscribed = default;
            Option<long?> replied = default;
            Option<long?> accepted = default;
            Option<long?> rejected = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "date":
                            date = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "requests":
                            requests = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "delivered":
                            delivered = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "hardBounces":
                            hardBounces = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "softBounces":
                            softBounces = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "blocked":
                            blocked = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "unsubscribed":
                            unsubscribed = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "replied":
                            replied = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "accepted":
                            accepted = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "rejected":
                            rejected = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!date.IsSet)
                throw new ArgumentException("Property is required for class GetTransacSmsReportReportsInner.", nameof(date));

            if (!requests.IsSet)
                throw new ArgumentException("Property is required for class GetTransacSmsReportReportsInner.", nameof(requests));

            if (!delivered.IsSet)
                throw new ArgumentException("Property is required for class GetTransacSmsReportReportsInner.", nameof(delivered));

            if (!hardBounces.IsSet)
                throw new ArgumentException("Property is required for class GetTransacSmsReportReportsInner.", nameof(hardBounces));

            if (!softBounces.IsSet)
                throw new ArgumentException("Property is required for class GetTransacSmsReportReportsInner.", nameof(softBounces));

            if (!blocked.IsSet)
                throw new ArgumentException("Property is required for class GetTransacSmsReportReportsInner.", nameof(blocked));

            if (!unsubscribed.IsSet)
                throw new ArgumentException("Property is required for class GetTransacSmsReportReportsInner.", nameof(unsubscribed));

            if (!replied.IsSet)
                throw new ArgumentException("Property is required for class GetTransacSmsReportReportsInner.", nameof(replied));

            if (!accepted.IsSet)
                throw new ArgumentException("Property is required for class GetTransacSmsReportReportsInner.", nameof(accepted));

            if (!rejected.IsSet)
                throw new ArgumentException("Property is required for class GetTransacSmsReportReportsInner.", nameof(rejected));

            if (date.IsSet && date.Value == null)
                throw new ArgumentNullException(nameof(date), "Property is not nullable for class GetTransacSmsReportReportsInner.");

            if (requests.IsSet && requests.Value == null)
                throw new ArgumentNullException(nameof(requests), "Property is not nullable for class GetTransacSmsReportReportsInner.");

            if (delivered.IsSet && delivered.Value == null)
                throw new ArgumentNullException(nameof(delivered), "Property is not nullable for class GetTransacSmsReportReportsInner.");

            if (hardBounces.IsSet && hardBounces.Value == null)
                throw new ArgumentNullException(nameof(hardBounces), "Property is not nullable for class GetTransacSmsReportReportsInner.");

            if (softBounces.IsSet && softBounces.Value == null)
                throw new ArgumentNullException(nameof(softBounces), "Property is not nullable for class GetTransacSmsReportReportsInner.");

            if (blocked.IsSet && blocked.Value == null)
                throw new ArgumentNullException(nameof(blocked), "Property is not nullable for class GetTransacSmsReportReportsInner.");

            if (unsubscribed.IsSet && unsubscribed.Value == null)
                throw new ArgumentNullException(nameof(unsubscribed), "Property is not nullable for class GetTransacSmsReportReportsInner.");

            if (replied.IsSet && replied.Value == null)
                throw new ArgumentNullException(nameof(replied), "Property is not nullable for class GetTransacSmsReportReportsInner.");

            if (accepted.IsSet && accepted.Value == null)
                throw new ArgumentNullException(nameof(accepted), "Property is not nullable for class GetTransacSmsReportReportsInner.");

            if (rejected.IsSet && rejected.Value == null)
                throw new ArgumentNullException(nameof(rejected), "Property is not nullable for class GetTransacSmsReportReportsInner.");

            return new GetTransacSmsReportReportsInner(date.Value!.Value!, requests.Value!.Value!, delivered.Value!.Value!, hardBounces.Value!.Value!, softBounces.Value!.Value!, blocked.Value!.Value!, unsubscribed.Value!.Value!, replied.Value!.Value!, accepted.Value!.Value!, rejected.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="GetTransacSmsReportReportsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getTransacSmsReportReportsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetTransacSmsReportReportsInner getTransacSmsReportReportsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getTransacSmsReportReportsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetTransacSmsReportReportsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getTransacSmsReportReportsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetTransacSmsReportReportsInner getTransacSmsReportReportsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("date", getTransacSmsReportReportsInner.Date.ToString(DateFormat));

            writer.WriteNumber("requests", getTransacSmsReportReportsInner.Requests);

            writer.WriteNumber("delivered", getTransacSmsReportReportsInner.Delivered);

            writer.WriteNumber("hardBounces", getTransacSmsReportReportsInner.HardBounces);

            writer.WriteNumber("softBounces", getTransacSmsReportReportsInner.SoftBounces);

            writer.WriteNumber("blocked", getTransacSmsReportReportsInner.Blocked);

            writer.WriteNumber("unsubscribed", getTransacSmsReportReportsInner.Unsubscribed);

            writer.WriteNumber("replied", getTransacSmsReportReportsInner.Replied);

            writer.WriteNumber("accepted", getTransacSmsReportReportsInner.Accepted);

            writer.WriteNumber("rejected", getTransacSmsReportReportsInner.Rejected);
        }
    }
}
