// <auto-generated>
/*
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using BrevoDotNet.Client;

namespace BrevoDotNet.Model
{
    /// <summary>
    /// SendSmtpEmailAttachmentInner
    /// </summary>
    public partial class SendSmtpEmailAttachmentInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendSmtpEmailAttachmentInner" /> class.
        /// </summary>
        /// <param name="url">Absolute url of the attachment (no local file).</param>
        /// <param name="content">Base64 encoded chunk data of the attachment generated on the fly</param>
        /// <param name="name">Required if content is passed. Name of the attachment</param>
        [JsonConstructor]
        public SendSmtpEmailAttachmentInner(Option<string?> url = default, Option<byte[]?> content = default, Option<string?> name = default)
        {
            UrlOption = url;
            ContentOption = content;
            NameOption = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Url
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UrlOption { get; private set; }

        /// <summary>
        /// Absolute url of the attachment (no local file).
        /// </summary>
        /// <value>Absolute url of the attachment (no local file).</value>
        /* <example>https://attachment.domain.com/myAttachmentFromUrl.jpg</example> */
        [JsonPropertyName("url")]
        public string? Url { get { return this.UrlOption; } set { this.UrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of Content
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<byte[]?> ContentOption { get; private set; }

        /// <summary>
        /// Base64 encoded chunk data of the attachment generated on the fly
        /// </summary>
        /// <value>Base64 encoded chunk data of the attachment generated on the fly</value>
        /* <example>b3JkZXIucGRm</example> */
        [JsonPropertyName("content")]
        public byte[]? Content { get { return this.ContentOption; } set { this.ContentOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Required if content is passed. Name of the attachment
        /// </summary>
        /// <value>Required if content is passed. Name of the attachment</value>
        /* <example>myAttachment.png</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendSmtpEmailAttachmentInner {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SendSmtpEmailAttachmentInner" />
    /// </summary>
    public class SendSmtpEmailAttachmentInnerJsonConverter : JsonConverter<SendSmtpEmailAttachmentInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="SendSmtpEmailAttachmentInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SendSmtpEmailAttachmentInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> url = default;
            Option<byte[]?> content = default;
            Option<string?> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "content":
                            content = new Option<byte[]?>(JsonSerializer.Deserialize<byte[]>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class SendSmtpEmailAttachmentInner.");

            if (content.IsSet && content.Value == null)
                throw new ArgumentNullException(nameof(content), "Property is not nullable for class SendSmtpEmailAttachmentInner.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class SendSmtpEmailAttachmentInner.");

            return new SendSmtpEmailAttachmentInner(url, content, name);
        }

        /// <summary>
        /// Serializes a <see cref="SendSmtpEmailAttachmentInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendSmtpEmailAttachmentInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SendSmtpEmailAttachmentInner sendSmtpEmailAttachmentInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sendSmtpEmailAttachmentInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SendSmtpEmailAttachmentInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendSmtpEmailAttachmentInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SendSmtpEmailAttachmentInner sendSmtpEmailAttachmentInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sendSmtpEmailAttachmentInner.UrlOption.IsSet && sendSmtpEmailAttachmentInner.Url == null)
                throw new ArgumentNullException(nameof(sendSmtpEmailAttachmentInner.Url), "Property is required for class SendSmtpEmailAttachmentInner.");

            if (sendSmtpEmailAttachmentInner.ContentOption.IsSet && sendSmtpEmailAttachmentInner.Content == null)
                throw new ArgumentNullException(nameof(sendSmtpEmailAttachmentInner.Content), "Property is required for class SendSmtpEmailAttachmentInner.");

            if (sendSmtpEmailAttachmentInner.NameOption.IsSet && sendSmtpEmailAttachmentInner.Name == null)
                throw new ArgumentNullException(nameof(sendSmtpEmailAttachmentInner.Name), "Property is required for class SendSmtpEmailAttachmentInner.");

            if (sendSmtpEmailAttachmentInner.UrlOption.IsSet)
                writer.WriteString("url", sendSmtpEmailAttachmentInner.Url);

            if (sendSmtpEmailAttachmentInner.ContentOption.IsSet)
            {
                writer.WritePropertyName("content");
                JsonSerializer.Serialize(writer, sendSmtpEmailAttachmentInner.Content, jsonSerializerOptions);
            }
            if (sendSmtpEmailAttachmentInner.NameOption.IsSet)
                writer.WriteString("name", sendSmtpEmailAttachmentInner.Name);
        }
    }
}
